### ISSUE TITLE
Change application.properties

### ISSUE THREAD

**Issue by 1Pali** [1Pali/be-fit-be#2]
Need to create heroku environment variables for url, user and password for DB. 
AC:
-investigate heroku https://devcenter.heroku.com/articles/config-vars
-modify backend to receive this variables

**Comment by peterkovac** [comment]
We found out that Spring Boot automatically reads url, username, password from SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, SPRING_DATASOURCE_PASSWORD
